name: postes_app_clean_architecture
description: Posts app clean Archetecture.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
